# Generated by Django 5.1.4 on 2024-12-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=100)),
                ('divisionName', models.CharField(blank=True, max_length=100, null=True)),
                ('titleName', models.CharField(blank=True, max_length=100, null=True)),
                ('sirName', models.CharField(blank=True, max_length=100, null=True)),
                ('givenName', models.CharField(blank=True, max_length=100, null=True)),
                ('postCode', models.CharField(blank=True, max_length=20, null=True)),
                ('address1', models.CharField(blank=True, max_length=100, null=True)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('tel', models.CharField(blank=True, max_length=100, null=True)),
                ('cell', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('email2', models.EmailField(blank=True, max_length=254, null=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('emailSend', models.BooleanField(default=False)),
                ('emailSendStamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('companyName',),
            },
        ),
    ]
