# Generated by Django 5.1.4 on 2024-12-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientmanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='eng',
            field=models.BooleanField(default=False),
        ),
    ]
