# Generated by Django 5.1.4 on 2024-12-05 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientmanage', '0002_client_comment_client_eng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='comment',
        ),
    ]
